
export const ADD_MOVIE='ADD_MOVIE'
export const SEARCH_MOVIE_KEYWORD='SEARCH_MOVIE_KEYWORD'
export const SEARCH_MOVIE_RATE='SEARCH_MOVIE_RATE'
export const DELETE_MOVIE='DELETE_MOVIE'
export const EDIT_MOVIE='EDIT_MOVIE'

